machine_info:
  name: "station_clr_tp2"
  mode_operation: "station"
  ip: "192.168.0.10"
  port: 8000
  port_machine_state: 8001
  time_out: 1000.0
  frequency: 2.0
  register:
    machine_data: 'DM300'
    dispenser_control: 'DM310'
    ingestor_control: 'DM311'
    request_type: 'D312'
  bit:
    dispenser_trigger: 'MR300'
    ingestor_trigger: 'MR301'
    request_delivery: 'MR302'
    station_states: 'M501'

  stations:
    clr001--dropoff: 'M501'
    clr002--dropoff: 'M502'
    clr003--dropoff: 'M503'
    clr004--dropoff: 'M504'
    clr005--dropoff: 'M505'