module MachineFleetData
{
  module DeviceMode_Constants
  {
    const unsigned long MODE_IDLE = 0;
    const unsigned long MODE_ACCEPT_DOCKIN = 1;
    const unsigned long MODE_ROBOT_DOCKED_IN = 2;
    const unsigned long MODE_ACCEPT_DOCKOUT = 3;
    const unsigned long MODE_CANCEL = 4;
    const unsigned long MODE_ROBOT_ERROR = 5;
  };
  module MachineRequest_Constants
  {
    const unsigned long REQUEST_DISPENSER = 0;
    const unsigned long REQUEST_INGESTOR = 1;
  };
  module MachineState_Constants
  {
    const unsigned long MODE_UNKNOWN = 0;
    const unsigned long MODE_HUMAN = 1;
    const unsigned long MODE_AGV = 2;
    const unsigned long MODE_ERROR = 3;
    const unsigned long MODE_EMERGENCY = 4;
  };
  module StationRequest_Constants
  {
    const unsigned long TYPE_PICKUP = 0;
    const unsigned long TYPE_DROPOFF = 1;
    const unsigned long MODE_EMPTY = 0;
    const unsigned long MODE_FILLED = 1;
  };
  module StationState_Constants
  {
    const unsigned long MODE_EMPTY = 0;
    const unsigned long MODE_FILLED = 1;
  };
  struct DeviceMode
  {
    unsigned long mode;
  };
  struct StationRequest
  {
    string machine_name;
    string station_name;
    unsigned long station_type;
    unsigned long mode;
  };
  struct StationState
  {
    string station_name;
    unsigned long mode;
  };
  struct MachineRequest
  {
    string machine_name;
    unsigned long request_type;
    DeviceMode request_mode;
    string request_id;
  };
  struct MachineState
  {
    string machine_name;
    unsigned long machine_mode;
    boolean request_pickup;
    DeviceMode dispenser_mode;
    string dispenser_request_id;
    boolean request_dropoff;
    DeviceMode ingestor_mode;
    string ingestor_request_id;
    sequence<StationState> station_states;
  };
};
