/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FleetMessages.h
  Source: FleetMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_FLEETMESSAGES_H_
#define _DDSL_FLEETMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif

#define MachineFleetData_DeliveryMode_Constants_MODE_PICKUP 0
#define MachineFleetData_DeliveryMode_Constants_MODE_DROPOFF 1
#define MachineFleetData_MachineMode_Constants_MODE_IDLE 0
#define MachineFleetData_MachineMode_Constants_MODE_PK_RELEASE 1
#define MachineFleetData_MachineMode_Constants_MODE_PK_CLAMP 2
#define MachineFleetData_MachineMode_Constants_MODE_DF_RELEASE 3
#define MachineFleetData_MachineMode_Constants_MODE_DF_CLAMP 4
#define MachineFleetData_MachineMode_Constants_MODE_ERROR 200
#define MachineFleetData_StationMode_Constants_MODE_EMPTY 0
#define MachineFleetData_StationMode_Constants_MODE_FILLED 1


typedef struct MachineFleetData_DeliveryMode
{
  uint32_t mode;
} MachineFleetData_DeliveryMode;

extern const dds_topic_descriptor_t MachineFleetData_DeliveryMode_desc;

#define MachineFleetData_DeliveryMode__alloc() \
((MachineFleetData_DeliveryMode*) dds_alloc (sizeof (MachineFleetData_DeliveryMode)));

#define MachineFleetData_DeliveryMode_free(d,o) \
dds_sample_free ((d), &MachineFleetData_DeliveryMode_desc, (o))


typedef struct MachineFleetData_MachineMode
{
  uint32_t mode;
} MachineFleetData_MachineMode;

extern const dds_topic_descriptor_t MachineFleetData_MachineMode_desc;

#define MachineFleetData_MachineMode__alloc() \
((MachineFleetData_MachineMode*) dds_alloc (sizeof (MachineFleetData_MachineMode)));

#define MachineFleetData_MachineMode_free(d,o) \
dds_sample_free ((d), &MachineFleetData_MachineMode_desc, (o))


typedef struct MachineFleetData_StationMode
{
  uint32_t mode;
} MachineFleetData_StationMode;

extern const dds_topic_descriptor_t MachineFleetData_StationMode_desc;

#define MachineFleetData_StationMode__alloc() \
((MachineFleetData_StationMode*) dds_alloc (sizeof (MachineFleetData_StationMode)));

#define MachineFleetData_StationMode_free(d,o) \
dds_sample_free ((d), &MachineFleetData_StationMode_desc, (o))


typedef struct MachineFleetData_DeliveryRequest
{
  char * machine_name;
  char * fleet_name;
  char * station_name;
  char * request_id;
  MachineFleetData_DeliveryMode mode;
} MachineFleetData_DeliveryRequest;

extern const dds_topic_descriptor_t MachineFleetData_DeliveryRequest_desc;

#define MachineFleetData_DeliveryRequest__alloc() \
((MachineFleetData_DeliveryRequest*) dds_alloc (sizeof (MachineFleetData_DeliveryRequest)));

#define MachineFleetData_DeliveryRequest_free(d,o) \
dds_sample_free ((d), &MachineFleetData_DeliveryRequest_desc, (o))


typedef struct MachineFleetData_MachineRequest
{
  char * machine_name;
  char * fleet_name;
  char * request_id;
  MachineFleetData_MachineMode mode;
} MachineFleetData_MachineRequest;

extern const dds_topic_descriptor_t MachineFleetData_MachineRequest_desc;

#define MachineFleetData_MachineRequest__alloc() \
((MachineFleetData_MachineRequest*) dds_alloc (sizeof (MachineFleetData_MachineRequest)));

#define MachineFleetData_MachineRequest_free(d,o) \
dds_sample_free ((d), &MachineFleetData_MachineRequest_desc, (o))


typedef struct MachineFleetData_MachineState
{
  char * machine_name;
  char * fleet_name;
  char * error_message;
  char * request_id;
  MachineFleetData_MachineMode mode;
} MachineFleetData_MachineState;

extern const dds_topic_descriptor_t MachineFleetData_MachineState_desc;

#define MachineFleetData_MachineState__alloc() \
((MachineFleetData_MachineState*) dds_alloc (sizeof (MachineFleetData_MachineState)));

#define MachineFleetData_MachineState_free(d,o) \
dds_sample_free ((d), &MachineFleetData_MachineState_desc, (o))


typedef struct MachineFleetData_StationRequest
{
  char * machine_name;
  char * fleet_name;
  char * request_id;
  char * station_name;
  MachineFleetData_StationMode mode;
} MachineFleetData_StationRequest;

extern const dds_topic_descriptor_t MachineFleetData_StationRequest_desc;

#define MachineFleetData_StationRequest__alloc() \
((MachineFleetData_StationRequest*) dds_alloc (sizeof (MachineFleetData_StationRequest)));

#define MachineFleetData_StationRequest_free(d,o) \
dds_sample_free ((d), &MachineFleetData_StationRequest_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_FLEETMESSAGES_H_ */
