/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FleetMessages.h
  Source: FleetMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_FLEETMESSAGES_H_
#define _DDSL_FLEETMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif

#define MachineFleetData_DeviceMode_Constants_MODE_IDLE 0
#define MachineFleetData_DeviceMode_Constants_MODE_ACCEPT_DOCKIN 1
#define MachineFleetData_DeviceMode_Constants_MODE_ROBOT_DOCKED_IN 2
#define MachineFleetData_DeviceMode_Constants_MODE_ACCEPT_DOCKOUT 3
#define MachineFleetData_DeviceMode_Constants_MODE_CANCEL 4
#define MachineFleetData_DeviceMode_Constants_MODE_ROBOT_ERROR 5
#define MachineFleetData_MachineRequest_Constants_REQUEST_DISPENSER 0
#define MachineFleetData_MachineRequest_Constants_REQUEST_INGESTOR 1
#define MachineFleetData_MachineState_Constants_MODE_UNKNOWN 0
#define MachineFleetData_MachineState_Constants_MODE_HUMAN 1
#define MachineFleetData_MachineState_Constants_MODE_AGV 2
#define MachineFleetData_MachineState_Constants_MODE_ERROR 3
#define MachineFleetData_MachineState_Constants_MODE_EMERGENCY 4
#define MachineFleetData_StationRequest_Constants_TYPE_PICKUP 0
#define MachineFleetData_StationRequest_Constants_TYPE_DROPOFF 1
#define MachineFleetData_StationRequest_Constants_MODE_EMPTY 0
#define MachineFleetData_StationRequest_Constants_MODE_FILLED 1
#define MachineFleetData_StationState_Constants_MODE_EMPTY 0
#define MachineFleetData_StationState_Constants_MODE_FILLED 1


typedef struct MachineFleetData_DeviceMode
{
  uint32_t mode;
} MachineFleetData_DeviceMode;

extern const dds_topic_descriptor_t MachineFleetData_DeviceMode_desc;

#define MachineFleetData_DeviceMode__alloc() \
((MachineFleetData_DeviceMode*) dds_alloc (sizeof (MachineFleetData_DeviceMode)));

#define MachineFleetData_DeviceMode_free(d,o) \
dds_sample_free ((d), &MachineFleetData_DeviceMode_desc, (o))


typedef struct MachineFleetData_StationRequest
{
  char * machine_name;
  char * station_name;
  uint32_t station_type;
  uint32_t mode;
} MachineFleetData_StationRequest;

extern const dds_topic_descriptor_t MachineFleetData_StationRequest_desc;

#define MachineFleetData_StationRequest__alloc() \
((MachineFleetData_StationRequest*) dds_alloc (sizeof (MachineFleetData_StationRequest)));

#define MachineFleetData_StationRequest_free(d,o) \
dds_sample_free ((d), &MachineFleetData_StationRequest_desc, (o))


typedef struct MachineFleetData_StationState
{
  char * station_name;
  uint32_t mode;
} MachineFleetData_StationState;

extern const dds_topic_descriptor_t MachineFleetData_StationState_desc;

#define MachineFleetData_StationState__alloc() \
((MachineFleetData_StationState*) dds_alloc (sizeof (MachineFleetData_StationState)));

#define MachineFleetData_StationState_free(d,o) \
dds_sample_free ((d), &MachineFleetData_StationState_desc, (o))


typedef struct MachineFleetData_MachineRequest
{
  char * machine_name;
  uint32_t request_type;
  MachineFleetData_DeviceMode request_mode;
  char * request_id;
} MachineFleetData_MachineRequest;

extern const dds_topic_descriptor_t MachineFleetData_MachineRequest_desc;

#define MachineFleetData_MachineRequest__alloc() \
((MachineFleetData_MachineRequest*) dds_alloc (sizeof (MachineFleetData_MachineRequest)));

#define MachineFleetData_MachineRequest_free(d,o) \
dds_sample_free ((d), &MachineFleetData_MachineRequest_desc, (o))

typedef struct MachineFleetData_MachineState_station_states_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MachineFleetData_StationState *_buffer;
  bool _release;
} MachineFleetData_MachineState_station_states_seq;

#define MachineFleetData_MachineState_station_states_seq__alloc() \
((MachineFleetData_MachineState_station_states_seq*) dds_alloc (sizeof (MachineFleetData_MachineState_station_states_seq)));

#define MachineFleetData_MachineState_station_states_seq_allocbuf(l) \
((MachineFleetData_StationState *) dds_alloc ((l) * sizeof (MachineFleetData_StationState)))


typedef struct MachineFleetData_MachineState
{
  int32_t sec;
  uint32_t nanosec;
  char * machine_name;
  uint32_t machine_mode;
  bool request_pickup;
  MachineFleetData_DeviceMode dispenser_mode;
  char * dispenser_request_id;
  bool request_dropoff;
  MachineFleetData_DeviceMode ingestor_mode;
  char * ingestor_request_id;
  MachineFleetData_MachineState_station_states_seq station_states;
} MachineFleetData_MachineState;

extern const dds_topic_descriptor_t MachineFleetData_MachineState_desc;

#define MachineFleetData_MachineState__alloc() \
((MachineFleetData_MachineState*) dds_alloc (sizeof (MachineFleetData_MachineState)));

#define MachineFleetData_MachineState_free(d,o) \
dds_sample_free ((d), &MachineFleetData_MachineState_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_FLEETMESSAGES_H_ */
